##Architecture to run automated tests on - {32, 64}
autotest.archtype=6
##First version of Eclipse to run automated tests on - {Mars, Neon, Oxygen}
autotest.eclipse1=Oxygen
##JDK to use for automated tests - {IBM 7, IBM 7.1, IBM 8, Oracle 7, Oracle 8, Oracle 9}
autotest.java=IBM 8
##Platform to run automated tests on - {Windows, Linux}
autotest.platform=Windows
disable.run.signjar=true
ebc.env.blueprint=[UBUNTU16.04][X86][Docker][Git]
ebc.env.groups=X86Cloud
ebc.env.order=LIBERTY-ISOLATED-CLOUD-PROD-HDC,LIBERTY-ISOLATED-CLOUD-BACKUP-HDC,UCDFOREBC02
env.env.groups=X86Cloud
gsa.base.dir=/wdt/dev/openlibertytools_personal
gsa.server=libfsfe06.hursley.ibm.com
image.gsa.server=libfsfe06.hursley.ibm.com
level_tag=personal
olt_build_type=personal
##The build will append "${base_targetPlatform}.zip" to this URL to determine from where to download the target platform
target.platform.baseurl=http://wdt-targetplatform-host.rtp.raleigh.ibm.com:9099/file-server/files?f=
year.regexp=(200[0-9]|201[0-9]|202[0-9])\\s?,?\\s?(200[0-9]|201[0-9]|202[0-9])?
year.regexp.2=(200[0-9]|201[0-8]|202[0-9])\s?,?\s?(200[0-9]|201[0-8]|202[0-9])?