async.thread.count=4
base_targetPlatform=target_platform_oxygen_3
BUILD_LOG=build.log
##build, removeLibertyBuildComponents, tagAndPromote
build.stub.target=build
##nightly or release
build.type=nightly
##Remove the '.disabled' suffix to re-enable autofvt.zip creation
create.autofvt.zip.disabled=false
create.liberty.adapter=false
##Clean up output/results after FAT run
delete.run.fats=true
dhe_server=9.214.184.249
disable.run.buildFatTests=true
disable.run.buildSamples=true
disable.run.checkCopyrightwdt=true
disable.run.createOffering=true
disable.run.fat.async.test.main=true
disable.run.generateAndPublishHTMLcopyrightReport=true
disable.run.generateNonBetaWDTUpdateSite=true
disable.run.packagePII=true
##false if publish update site into DHE
disable.run.publishDHE=false
disable.run.runBvtTests=true
disable.run.runExtraTests=true
disable.run.runFatTestsAfterBuild=true
disable.run.runFixList=true
disable.run.runUnitTests=true
disable.run.spawnCloudBuildPackBuild=true
disable.run.startChildBuilds=true
ebc.priority=100
ebc.shortlist=releaseJBE.yml
extra.ant.options=
##all, none, or a comma-separated list of FAT project names.
fat.buckets.to.run=none
##lite or full
fat.test.mode=lite
FILE_PREFIX=openlibertytools-25.2.v
git.clone.download.server=libfsfe06.hursley.ibm.com
git.clone.liberty.checkout.branch=development
git.clone.liberty.repository.sshUrl=git@github.ibm.com:was-liberty/wdt-clone-of-liberty.git
git.clone.olt.checkout.branch=integration
git.clone.olt.remote.branch=main
git.clone.olt.repository.sshUrl=git@github.com:OpenLiberty/open-liberty-tools.git
##Skip build if no commit is found. Following values are allowed : 1 day ago; 2 days ago; n days ago; 1 week ago; 2 weeks ago; n weeks ago
git.clone.whatchanged=4 months ago
git.launcher.clone.branch=integration
git.launcher.clone.sshUrl=git@github.ibm.com:${git.launcher.clone.username}/rtc-build-launcher.git
git.launcher.clone.username=websphere
global.trace.spec=logservice=all=enabled
gsa.clone.dir.uri=/liberty/prereqs/GHEWDTClone
gsa.clone.liberty.prefix=LibertyGitClone
gsa.clone.prefix=WDTGitClone
gsaUpload=true
ignoreBuildStatusForAsyncLaunch=true
ignoreBuildStatusForAsyncLaunch=true
INFO_JSON=info.json
iberty.fs.management=true
nagios.monitoring=true
##The build file for OLT, build-openlibertytools.xml, build-wdt.xml
passthrough.build.file.name=build-openlibertytools.xml
##olt
product.name=wdt
run.chkpii=false
##Create zipped image
run.createImage=false
##create plugin for IBM workload deployer
run.createIwdImage=false
##If true, run FAT in async build
run.fat.async=false
##Run findbugs target
run.findbugs=false
run.fixlist.wdt=false
##If true run the media verification tests
run.mvt=false
soe.reporting.publish=false
##If true, will build and test z-specific parts of Liberty. If you do set this, make sure there are no spaces in your workspace name! Under normal circumstances, there should be no need to set this to be true.
spawn.zos=false
##Set to true to force all bvt and fat logs to be uploaded even if tests pass.
team.scm.loadComponents=upload.all.test.logs=false
use.libertyfs.jvm.cache=true
use.scp=true
wait.for.async=true
zos.async.target.name=X Open Asynchronous component tests on z/OS - Liberty
##The name of the z/OS build definition to use.
zos.target.name=X Open Asynchronous z/OS packaging build - Liberty