disable.run.signjar=false
git.clone.checkout.branch=integration
##/openlibertytools/dev
gsa.base.dir=/wdt/dev/openlibertytools
gsa.server=libfsfe04.hursley.ibm.com
olt_build_type=nightly
##The build will append "${base_targetPlatform}.zip" to this URL to determine from where to download the target platform
target.platform.baseurl=http://libh-wdt-targetplatform-1.fyre.ibm.com:9099/file-server/files?f=
test.bucket=wdt-bvt,wdt-regression
year.regexp=(200[0-9]|202[0-9])\\s?,?\\s?(200[0-9]|202[0-9])?
year.regexp.2=(200[0-9]|202[0-9])\s?,?\s?(200[0-9]|202[0-9])?