type: pipeline_definition
product: Liberty
name: Open Liberty Tools Official Release Build
description: A scheduled build run to release Open Liberty Tools
triggers:
- type: manual
  description: "Monitored trigger to run the release build. Used to run the Open Liberty Tools release build ahead of schedule"
  triggerName: "Manual"
  triggerRank: 100
  groups: ["WDT"]
  propertyDefinitions:
  - name: base_targetPlatform
    isRequired: true
    defaultValue: "target_platform_oxygen_3"
    description: "e.g. target_platform_oxygen_3"
    steps:
    - stepName: RTC-Parent
  - name: disable.run.signjar
    isRequired: true
    defaultValue: "false"
    description: ""
    steps:
    - stepName: RTC-Parent
  - name: git.clone.checkout.branch
    isRequired: true
    defaultValue: "integration"
    description: ""
    steps:
    - stepName: RTC-Parent
  - name: git.clone.download.server
    isRequired: true
    defaultValue: "libfsfe06.hursley.ibm.com"
    description: ""
    steps:
    - stepName: RTC-Parent
  - name: git.clone.liberty.checkout.branch
    isRequired: true
    defaultValue: "development"
    description: ""
    steps:
    - stepName: RTC-Parent
  - name: git.clone.liberty.repository.sshUrl
    isRequired: true
    defaultValue: "git@github.ibm.com:was-liberty/wdt-clone-of-liberty.git"
    description: ""
    steps:
    - stepName: RTC-Parent
  - name: git.clone.olt.checkout.branch
    isRequired: true
    defaultValue: "integration"
    description: ""
    steps:
    - stepName: RTC-Parent
  - name: git.clone.olt.remote.branch
    isRequired: true
    defaultValue: "main"
    description: ""
    steps:
    - stepName: RTC-Parent
  - name: git.clone.olt.repository.sshUrl
    isRequired: true
    defaultValue: "git@github.com:OpenLiberty/open-liberty-tools.git"
    description: ""
    steps:
    - stepName: RTC-Parent
  - name: git.launcher.clone.branch
    isRequired: true
    defaultValue: "integration"
    description: ""
    steps:
    - stepName: RTC-Parent
  - name: git.launcher.clone.sshUrl
    isRequired: true
    defaultValue: "git@github.ibm.com:${git.launcher.clone.username}/rtc-build-launcher.git"
    description: ""
    steps:
    - stepName: RTC-Parent
  - name: git.launcher.clone.username
    isRequired: true
    defaultValue: "websphere"
    description: ""
    steps:
    - stepName: RTC-Parent
  - name: gsa.base.dir
    isRequired: true
    defaultValue: "/wdt/dev/openlibertytools"
    description: "Output build directory"
    steps:
    - stepName: RTC-Parent
  - name: gsa.server
    isRequired: true
    defaultValue: "libfsfe04.hursley.ibm.com"
    description: ""
    steps:
    - stepName: RTC-Parent
  - name: level_tag
    isRequired: true
    defaultValue: "25.2"
    description: "level that is used for output file e.g. 25.2"
    steps:
    - stepName: RTC-Parent  

# - type: schedule
#   description: "Scheduled Open Liberty Tools release build."
#   triggerName: "Scheduled"
#   triggerRank: 100
#   groups: ["WDT"]
#   triggerThreshold: 100
#   at:
#     - Sun Mon Tue Wed Thu Fri Sat 00:00

steps:
- stepName: RTC-Parent
  coreStep: true
  workType: RTC
  projectName: "OLT GHE Release Build"
  timeoutInMinutes: 180
  