/*******************************************************************************
 * Copyright (c) 2017 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
/*******************************************************************************
 * Copyright (c) 2017 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//

package wasdev.sample.jaxws.ejb.webservicesxml.webclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "CountdownImpl", targetNamespace = "http://webservicesxml.ejb.jaxws.sample.wasdev/")
@XmlSeeAlso({
             ObjectFactory.class
})
public interface CountdownImpl {

    /**
     * 
     * @param arg0
     * @return
     *         returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countdownfromme", targetNamespace = "http://webservicesxml.ejb.jaxws.sample.wasdev/",
                    className = "wasdev.sample.jaxws.ejb.webservicesxml.webclient.Countdownfromme")
    @ResponseWrapper(localName = "countdownfrommeResponse", targetNamespace = "http://webservicesxml.ejb.jaxws.sample.wasdev/",
                     className = "wasdev.sample.jaxws.ejb.webservicesxml.webclient.CountdownfrommeResponse")
    @Action(input = "http://webservicesxml.ejb.jaxws.sample.wasdev/CountdownImpl/countdownfrommeRequest",
            output = "http://webservicesxml.ejb.jaxws.sample.wasdev/CountdownImpl/countdownfrommeResponse")
    public String countdownfromme(
                                  @WebParam(name = "arg0", targetNamespace = "") int arg0);

}
