/*******************************************************************************
 * Copyright (c) 2017 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
/*******************************************************************************
 * Copyright (c) 2017 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//

package wasdev.sample.jaxws.ejb.webservicesxml.webclient;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the wasdev.sample.jaxws.ejb.webservicesxml.webclient package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Countdownfromme_QNAME = new QName("http://webservicesxml.ejb.jaxws.sample.wasdev/", "countdownfromme");
    private final static QName _CountdownfrommeResponse_QNAME = new QName("http://webservicesxml.ejb.jaxws.sample.wasdev/", "countdownfrommeResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: wasdev.sample.jaxws.ejb.webservicesxml.webclient
     * 
     */
    public ObjectFactory() {}

    /**
     * Create an instance of {@link Countdownfromme }
     * 
     */
    public Countdownfromme createCountdownfromme() {
        return new Countdownfromme();
    }

    /**
     * Create an instance of {@link CountdownfrommeResponse }
     * 
     */
    public CountdownfrommeResponse createCountdownfrommeResponse() {
        return new CountdownfrommeResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Countdownfromme }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://webservicesxml.ejb.jaxws.sample.wasdev/", name = "countdownfromme")
    public JAXBElement<Countdownfromme> createCountdownfromme(Countdownfromme value) {
        return new JAXBElement<Countdownfromme>(_Countdownfromme_QNAME, Countdownfromme.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountdownfrommeResponse }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://webservicesxml.ejb.jaxws.sample.wasdev/", name = "countdownfrommeResponse")
    public JAXBElement<CountdownfrommeResponse> createCountdownfrommeResponse(CountdownfrommeResponse value) {
        return new JAXBElement<CountdownfrommeResponse>(_CountdownfrommeResponse_QNAME, CountdownfrommeResponse.class, null, value);
    }

}
